openapi: 3.0.0
info:
  title: essence
  version: '1.0'
  description: This is API Document Sample.
  contact:
    name: ykoba
servers:
  - url: 'http://localhost:3000'
    description: local
paths:
  /users/me:
    get:
      summary: プロフィール取得API
      tags:
        - user
      responses: {}
      operationId: get-users-me
      parameters: []
    put:
      summary: 会員登録API
      tags:
        - user
      responses: {}
      operationId: put-users-me
    post:
      summary: プロフィール更新API
      tags:
        - user
      responses: {}
      operationId: post-users-me
    delete:
      summary: 退会API
      tags:
        - user
      responses: {}
      operationId: delete-users-me
components:
  schemas: {}
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []
